# Generated by Django 3.1.7 on 2021-04-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='how_much_growth',
            field=models.CharField(choices=[('0cm', 'GROW0cm'), ('1cm', 'GROW1cm'), ('2cm', 'GROW2cm')], default='0cm', max_length=3),
        ),
    ]
