# Generated by Django 3.1.7 on 2021-04-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiary', '0002_content_how_much_growth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='how_much_growth',
        ),
        migrations.AddField(
            model_name='content',
            name='growth',
            field=models.CharField(choices=[('0cm', '0cm'), ('1cm', '1cm'), ('2cm', '2cm')], default='0cm', max_length=3),
        ),
    ]
