# Generated by Django 3.1.7 on 2021-04-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiary', '0003_auto_20210405_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='growth',
            field=models.CharField(choices=[('_0cm', '0cm'), ('_1cm', '1cm'), ('_2cm', '2cm')], default='_0cm', max_length=4),
        ),
    ]
