# Generated by Django 3.1.7 on 2021-04-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiary', '0004_auto_20210405_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='growth',
            field=models.CharField(choices=[('0cm', '0cm'), ('1cm', '1cm'), ('2cm', '2cm')], default='0cm', max_length=4),
        ),
    ]
