# Generated by Django 3.1.7 on 2021-05-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiary', '0005_auto_20210405_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='growth',
        ),
        migrations.AddField(
            model_name='content',
            name='cat',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='content',
            name='eating',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='content',
            name='how_much',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='content',
            name='place',
            field=models.CharField(choices=[('정문', '정문'), ('후문', '후문'), ('다산관', '다산관'), ('K관', 'K관'), ('로욜라', '로욜라'), ('리치과학관', '리치과학관')], default='정문', max_length=5),
        ),
        migrations.AddField(
            model_name='content',
            name='state',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
